# Run sudo pre-commit install --overwrite
# Needs pip install pre-commit

repos:
- repo: local
  hooks:
  - id: run-tests
    name: Run Tests without Error
    entry: python -m unittest discover -s tests
    language: system
    pass_filenames: false # Otherwise the discovered files will be passed as arguments
  - id: run-script
    name: Run Tennis Script without Error
    entry:  venv/Scripts/python.exe tennis_validation.py
    language: python
  - id: run-version
    name: Version was updated since last commit (see setup.py)
    entry: venv/Scripts/python.exe version_validation.py
    language: python