site_name: VR Gaze
site_url: https://github.com/vrijeuniversiteit/vrgaze
repo_url: https://github.com/vrijeuniversiteit/vrgaze
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/logo_inv.png
  palette:
    primary: blue

nav:
  - Home: index.md
  - Setup Python: setup_python.md
  - Tennis: tennis.md # All classes with docstrings """ are discovered
  - Contribute: contribute.md
  - Having Issues?: issues.md

plugins:
  - search
  - mkdocstrings:
      watch:
        - vrgaze
      handlers:
        python: # Needs to have a handler so that classes are discovered
          options:
            show_source: true
            show_submodules: true

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
      check_paths: true